// src/routes/(unlocked)/generate/+page.svelte
<script lang="ts">
    import { invoke } from "@tauri-apps/api/core";
    import { Button } from "$lib/components/ui/button";
    import Textarea from '@/custom-components/TextArea2.svelte';
    import { Input } from "@/components/ui/input";
    import { toast } from "svelte-sonner";
	import { get_private_keys, get_public_keys } from "@/api";
	import { onMount } from "svelte";
    import * as Select from "$lib/components/ui/select";
    import type { Snapshot } from './$types';
    import { writable } from "svelte/store";
    import { browser } from "$app/environment";
    import { restorable } from "@/helper";
	
	
	
    
    type Output ={
        private_key:string,
        public_key:string
    }

    let passKey = '';
    let generating: boolean = false;

    //make the next few lines repeatable
    const out = restorable("generated_keys", {private_key:'', public_key:''});
    
    async function generate() {
        try {
            generating = true;

            out.set(await invoke('generate_key', {passKey}) as Output);
            
        } catch (err) {
            console.error(err);
            out.set( {
                private_key:'',
                public_key:''
            });
  
            toast.error(`Error generating key: ${err}`); 
        } finally {
            generating = false;
        }
    }
</script>

<div class="p-5 flex flex-col gap-2 w-full h-full">
    <Input placeholder="Name" />
    <Input placeholder="email" type="email" />
    <Input placeholder="Password" type="password" />
    <Button  disabled={generating} on:click={() => generate()}>{generating ? "Generating...":"Generate"}</Button>
    <Textarea class="w-full h-full" disabled value={$out.private_key} placeholder="Private Key" />
    <Textarea class="w-full h-full " disabled value={$out.public_key} placeholder="Public Key" />
    
  

</div>

// src/routes/pgp/Generate.tsx
import { Button} from "@/components/ui/button";
import { TextAreaWithCopy } from "@/components/mod-ui/copy-text-area";
import { GeneratePGPKeys } from "@/lib/api/pgp";
import { useState } from "react";
import { GeneratePGPKeysResponse } from "@/lib/api/types";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog"
import { Input } from "@/components/ui/input";
import { useToast } from "@/hooks/use-toast";


export default function Generate() {
  const [loadingGeneration,setLoadingGeneration] = useState(false);
  const toast = useToast();
  const [keyPair,setKeyPair] = useState<GeneratePGPKeysResponse |undefined>(undefined);

  return (
    <section className="container flex flex-col h-full gap-2 p-5">

      <Button disabled={loadingGeneration} onClick={async ()=> {
        setLoadingGeneration(true);
        try{
          let out = await GeneratePGPKeys();
          setKeyPair(out);
        }catch(err){
          console.error(err);
          toast.toast({
            variant: "destructive",
            title: "Uh oh! Something went wrong.",
            description: err as string,
          })
        }

        setLoadingGeneration(false);

  

      }} >
       {loadingGeneration ? "Generating..." : "Generate Key Pair"} 
      </Button>

      <TextAreaWithCopy className="flex-grow h-full" value={keyPair?.private_key} disabled/>
      <TextAreaWithCopy className="flex-grow h-full"  value={keyPair?.public_key} disabled/>

      <Dialog >
        <DialogTrigger><Button className="w-full" variant={"secondary"}>Save Key Pair</Button></DialogTrigger>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>Save Key</DialogTitle>
            <DialogDescription>
              Save your key pair into your identities database.
            </DialogDescription>
          </DialogHeader>
          <Input placeholder="Name" />
          <Input placeholder="Description" />
          <div className="flex gap-2">
            <Button className="w-full" variant={"default"} onClick={()=> {

            }}>Save</Button>
          </div>
        </DialogContent>
      </Dialog>


    </section>
  );
}
